spring:
#  config:
#    activate:
#      on-profile: prod
  datasource:
    # url: jdbc:mysql://RDS엔드포인트:3306/DB스키마명?autoReconnect=true
    # autoReconnect : 시간이 지나면 DB 연결이 자동으로 끊기는데 이를 막기 위함
    url: jdbc:mysql://wanteddb.cse28wj5y9fo.ap-northeast-2.rds.amazonaws.com:3306/prod_insta_db?autoReconnect=true
    username: admin
    password: rc_wanted
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
  sql:
    init:
      platform: mysql
